name: Terraform Formatting
description: Ensures proper Terraform formatting.

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Format
      id: fmt
      run: terraform fmt
      shell: bash
      continue-on-error: true

    - name: Commit Formatting Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply terraform fmt changes
