name: test-vpc
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - 'vpc/**.tf'

permissions:
  id-token: write

jobs:
  terraform-formatting:
    defaults:
      run:
          working-directory: './vpc/'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt
        continue-on-error: true

      - name: Commit Formatting Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply terraform fmt changes

  terraform-scanning:
    defaults:
      run:
          working-directory: './vpc/'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: latest

			- name: Show version
				run: tflint --version

			- name: Init TFLint
				run: tflint --init
				env:
					# https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
					GITHUB_TOKEN: ${{ github.token }}

			- name: Run TFLint
				run: tflint -f compact

  terraform-tests:
    runs-on: ubuntu-latest
    #if: steps.auto-commit-action.outputs.changes_detected == 'false'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: us-west-2
          # 21600 seconds == 6 hours
          # 1800 seconds == 30 minutes
          role-duration-seconds: 1800
      # terraform fmt, tf validate, tflint, chekov
      - name: Run Common Terraform Tests
        uses: defenseunicorns/uds-common-workflows/.github/actions/terraform-test@fix-setup-go
        with:
          test_retry: 1
          test_dir: ./vpc/test
        env:
          BACKEND_BUCKET: ${{ vars.BACKEND_BUCKET }}
          BACKEND_KEY: ${{ vars.BACKEND_KEY }}vpc.tfstate
          BACKEND_REGION: ${{ vars.BACKEND_REGION }}
          BACKEND_DYNAMODB_TABLE: ${{ vars.BACKEND_DYNAMODB_TABLE }}
